// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace JSONObjects
{

    public class Dnd
    {

        [JsonProperty("dnd_enabled")]
        public bool DndEnabled { get; set; }

        [JsonProperty("next_dnd_start_ts")]
        public int NextDndStartTs { get; set; }

        [JsonProperty("next_dnd_end_ts")]
        public int NextDndEndTs { get; set; }

        [JsonProperty("snooze_enabled")]
        public bool SnoozeEnabled { get; set; }
    }

}
