// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace JSONObjects
{

    public class Icon
    {

        [JsonProperty("image_34")]
        public string Image34 { get; set; }

        [JsonProperty("image_44")]
        public string Image44 { get; set; }

        [JsonProperty("image_68")]
        public string Image68 { get; set; }

        [JsonProperty("image_88")]
        public string Image88 { get; set; }

        [JsonProperty("image_102")]
        public string Image102 { get; set; }

        [JsonProperty("image_132")]
        public string Image132 { get; set; }

        [JsonProperty("image_230")]
        public string Image230 { get; set; }

        [JsonProperty("image_original")]
        public string ImageOriginal { get; set; }
    }

}
