// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace JSONObjects
{

    public class Response
    {

        [JsonProperty("ok")]
        public bool Ok { get; set; }

        [JsonProperty("self")]
        public Self Self { get; set; }

        [JsonProperty("team")]
        public Team Team { get; set; }

        [JsonProperty("latest_event_ts")]
        public string LatestEventTs { get; set; }

        [JsonProperty("channels")]
        public Channel[] Channels { get; set; }

        [JsonProperty("groups")]
        public Group[] Groups { get; set; }

        [JsonProperty("ims")]
        public Im[] Ims { get; set; }

        [JsonProperty("cache_ts")]
        public int CacheTs { get; set; }

        [JsonProperty("subteams")]
        public Subteams Subteams { get; set; }

        [JsonProperty("dnd")]
        public Dnd Dnd { get; set; }

        [JsonProperty("users")]
        public User[] Users { get; set; }

        [JsonProperty("cache_version")]
        public string CacheVersion { get; set; }

        [JsonProperty("cache_ts_version")]
        public string CacheTsVersion { get; set; }

        [JsonProperty("bots")]
        public Bot[] Bots { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }
    }

}
