// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace JSONObjects
{

    public class Subteams
    {

        [JsonProperty("self")]
        public object[] Self { get; set; }

        [JsonProperty("all")]
        public object[] All { get; set; }
    }

}
