// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace JSONObjects
{

    public class WhoCanPostInSharedChannels
    {

        [JsonProperty("type")]
        public string[] Type { get; set; }
    }

}
